### ISSUE TITLE
How to stringent the criteria for variable selection?

### ISSUE THREAD

**Issue by nikosGeography** [robingenuer/VSURF#11]
Hi, I was wondering if there is a way to make the variable selection more stringent (i.e., to select even fewer predictors).

Using the default parameters, the model selects 13/25 variables.

set.seed(23445)
vars <- VSURF(df[, 2:length(df)],
              df[, 1], 
              parallel = TRUE,
              RFimplem = "ranger")

I tried to increase the nsd(), ntree.thres(), ntree.pred() and other parameters but the result was mostly the same (13/25). Could you please advice me on how can I proceed?

R 4.4.1, RStudio 2024.04.2 Build 764, Windows 11.

**Comment by robingenuer** [comment]
Hi,
Thanks for your interest in the VSURF package.

As a general advice, I would recommend to look at the graphs given by the plot() method of the package. Especially, the two graphs at the bottom (interpretation at the left, and prediction at the right) show how the OOB error varies against the number of important variables in the RF models.

About the parameters: increasing nsd has the effect of reducing the number of selected variables at the interpretation step, and nmj at the prediction step (actually, you can use the tune() method to try different nsd values, which avoids to re-run all RF models computation).

Finally, even I do not know your data at all, I would say that if 13 variables were kept among your initial 25 variables, maybe it means that they are all useful to predict the outcome. Another way to stringent more the variable selection would be to look at the variable importance values of variables selected at the prediction step, and make a choice based on these observed values.

I hope it will help !

**Comment by nikosGeography** [comment]
This is a great advice! Thank you, I can close the issue.

Best wishes.
