### ISSUE TITLE
Subscripting?

### ISSUE THREAD

**Issue by mjg4243** [robingenuer/VSURF#2]
This does not happen with "toys" -- but perhaps someone who knows more about the nuts and bolts of R can see something that needs fixing.

I am processing the Boston housing data but modified to work with another package.  In my "boston" the dependent variable is in the first column and the predictors are in the others.  To simplify things while trying this out, I am keeping the "toys" in the syntax, as you can see here.

toys$x=boston[1:50,2:ncol(boston)]
toys$y=boston[1:50,1]
toys.vsurf <- VSURF(toys$x, toys$y, parallel= T)
summary(toys.vsurf)
## 
## 
## 3 variables at prediction step (in 6.6 secs)

And this works just fine, as you can see.  But here is the odd part.  I wonder which 3 variables have been selected --

toys.vsurf$varselect.pred
## [1] 10  7 13

plot(toys.vsurf, var.names=T)

But in the plot I get "predictive models" vs. OOB error showing V11  V8  V14.  One off.  It makes sense to me, because "toys$x" consists of columns 2 through 14 of the original data frame "boston,"   and I can see how the column names might have just been preserved.  I also notice that in the original "toys$x" from the original file "toys" the columns are numbered from V1 up.  Probably just needs a "work-around," don't you think?  But I don't know R well enough to figure out how to do that.

Best regards

Mike Gallagher

**Comment by robingenuer** [comment]
Dear Mike Gallagher,
I'm truly sorry for the delay of my answer.

Indeed, the numbers in "varselect.pred" are the indices of the input "x" in the first argument of VSURF function.
If you want to get the names of the input variables (instead of the indices) you could use:
names(toys$x)[toys.vsurf$varselect.pred]
which would give you V11 V8 V14. And that is what is done in the plot function (with var.names = TRUE).

According to me, there is no issue here. But maybe I do not correctly understand your point ?

Kind regards,
Robin

**Comment by mjg4243** [comment]
Away from computer for s few days but will look at this and let you know.  Cheers

Sent from Yahoo Mail on Android 

  On Sun, Mar 6, 2016 at 9:22 AM, Robin Genuernotifications@github.com wrote:  
Dear Mike Gallagher,
I'm truly sorry for the delay of my answer.

Indeed, the numbers in "varselect.pred" are the indices of the input "x" in the first argument of VSURF function.
If you want to get the names of the input variables (instead of the indices) you could use:
names(toys$x)[toys.vsurf$varselect.pred]
which would give you V11 V8 V14. And that is what is done in the plot function (with var.names = TRUE).

According to me, there is no issue here. But maybe I do not correctly understand your point ?

Kind regards,
Robin

**Comment by mjg4243** [comment]
You did understand it, and answered it.  Many thanks. Mike Gallagher

```
  From: Robin Genuer <notifications@github.com>
```

 To: robingenuer/VSURF VSURF@noreply.github.com 
Cc: mjg4243 mjgallagher43@yahoo.com
 Sent: Sunday, March 6, 2016 10:22 AM
 Subject: Re: [VSURF] Subscripting? (#2)

Dear Mike Gallagher,
I'm truly sorry for the delay of my answer.Indeed, the numbers in "varselect.pred" are the indices of the input "x" in the first argument of VSURF function.
If you want to get the names of the input variables (instead of the indices) you could use:
names(toys$x)[toys.vsurf$varselect.pred]
which would give you V11 V8 V14. And that is what is done in the plot function (with var.names = TRUE).According to me, there is no issue here. But maybe I do not correctly understand your point ?Kind regards,
Robin—
