### ISSUE TITLE
ranger package

### ISSUE THREAD

**Issue by jbkunst** [robingenuer/VSURF#3]
Hi @robingenuer  Robin,

Nice package. Very intuitive the idea. 

Have you thinking about use [ranger](https://github.com/imbs-hl/ranger) instead of randomForest. I tested and made some benchmarks and I see a significant reduction of times. Is in your future work for this package made something about the performance?

Thanks and regards!

**Comment by robingenuer** [comment]
Hi Joshua,
Thank you for your recommendation.
I effectively plan to add the possibility to use the ranger package in VSURF.
My few tests confirm that on high dimensional datasets it could reduce significantly computation time.

Kind regards,
Robin

**Comment by jbkunst** [comment]
Hi Robin,

Thanks for your responde. Nices news! 

Regards!
