### ISSUE TITLE
Ranger implemetation

### ISSUE THREAD

**Issue by marcabrus** [robingenuer/VSURF#5]
Hi,
I'm trying the examples in order to benchmark RF implementation VS Ranger.
It seems that Random Forest is always more rapid than Ranger. for example:
```R
vacRangerInter <- VSURF(x = geneExpr, y = stimu, parallel = TRUE,
                      ncores = ncores, RFimplementation = "ranger",
                      clusterType = "ranger")
 summary(vacRangerInter)

 VSURF computation time: 8.2 mins 

 VSURF selected: 
	119 variables at thresholding step (in 52 secs)
	17 variables at interpretation step (in 6.8 mins)
	7 variables at prediction step (in 27.7 secs)

 VSURF ran in parallel on a ranger cluster and used 4 cores 
vacRF <- VSURF(x = geneExpr, y = stimu, parallel = TRUE, ncores = ncores)
 summary(vacRF)

 VSURF computation time: 1.2 mins 

 VSURF selected: 
	99 variables at thresholding step (in 34.2 secs)
	23 variables at interpretation step (in 31.6 secs)
	13 variables at prediction step (in 6.8 secs)

 VSURF ran in parallel on a PSOCK cluster and used 4 cores 
```
Did you experience the same issue? Are the example datasets too small to evaluate that?

**Comment by xenmind** [comment]
Can confirm for my dataset (200 odd features) that Ranger took significantly longer.

**Comment by robingenuer** [comment]
Dear @marcabrus and @xenmind,
I confirm this behavior for the ranger implementation.
This may be more deeply evaluated, but for what I
tried, this is caused by the fact that ranger is actually
longer than randomForest to compute variable
importance (whereas it is faster to built the RF predictor).

Since VSURF is based on variable importance
computation (in the first step), this partially explains
the difference in computation time between the two
implementations.

**Comment by marcabrus** [comment]
Good to know. Could be possible as far as you know to use for the first step RF and for the other two steps Ranger?  I usually do the three steps separately so I can save during the process so it could nor be a big deal.

**Comment by robingenuer** [comment]
That's a good point. If you perform the three steps separately, you can choose for each the RFimplementation parameter. Maybe ranger could give you a speed up for the second and third steps.

**Comment by robingenuer** [comment]
I have just added the possibility to run VSURF (the global function) with the choice of the RF implementation for each step: the RFimplem admits a vector of length 3 (one value for each step).
I also add the possibility to use Rborist (known for good results in the case of very high number of observations, a.k.a Big data framework).

**Comment by marcabrus** [comment]
It seems to me a great update! I will try also the new implementation. Thank you very much for your efforts.
