### ISSUE TITLE
Print names of selected variables after running the vsurf function

### ISSUE THREAD

**Issue by nikosGeography** [robingenuer/VSURF#7]
First of all, well done creating the package. It's really easy to follow and understand. My question is probably very simple. I have a `data.frame` containing a dependent and multiple independent variables for a regression task. After running the below code:

```
library(VSURF)

wd = "path/"

block.data = read.csv(paste0(wd, "block.data.csv"))

vars <- VSURF(block.data[, 2:27], 
              block.data$ntl, 
              parallel = TRUE, 
              ncores = detectCores() - 1, 
              clusterType = "PSOCK", 
              ntree = 501)

summary(vars)
```

I get this:

```
VSURF selected: 
	26 variables at thresholding step (in 28.6 mins)
	16 variables at interpretation step (in 39 mins)
	12 variables at prediction step (in 1.3 hours)

 VSURF ran in parallel on a PSOCK cluster and used 15 cores
```

If I type:
`vars$varselect.pred`

I get this:

`[1] 22 14  1  3 26 21  2  8 13 18 11  4`

My goal is to print the names of the selected covariates  and not their column number. Is this possible? 

If needed, I can share a small set of the `data.frame`.

**Comment by robingenuer** [comment]
Thanks for your positive feedback.
We didn't include the possibility to output the selected variables names. In your case I think the following command will give you the corresponding names:

`names(block.data[, 2:27])[vars$varselect.pred]`

It should outputs the names in the same order than the indices, e.g., from the most important to the least important variables.

**Comment by nikosGeography** [comment]
It works, thank you.
