### ISSUE TITLE
VSURF compatibility with data.table

### ISSUE THREAD

**Issue by nikosGeography** [robingenuer/VSURF#8]
First of all, thank you for creating this amazing packcage, keep up the good work. This is not an issue, just a recommendation about the compatibility of the `VSURF` and `data.table` packages. Normally, to read a csv file one can use the base `R` function `read.csv()`. But for larger files the `data.table` is way faster (see a comparison between the `read.csv()` and `fread()` functions [here](https://www.r-bloggers.com/2021/03/data-table-everything-you-need-to-know-to-get-you-started-in-r/)).

Recently, I switched to the `data.table` in order to read my csv files and while other packages (e.g., `ranger`, `tidymodels` etc) don't seem to have an issue with the package, `VSURF` returns an error when trying to run the `vsurf()` function. The error says:

`Error in df[, 2:length(df)] : object of type 'closure' is not subsettable`

When I read my csv using `read.csv()` the error disappears, which led me to believe that `VSURF` is incopatible with `data.table`. If you think that by making the package compatible with `data.table` is something worth doing it then you can keep this post open until you do it, otherwise feel free to close the issue.

Here is the code I am using:
```
library(data.table)
library(VSURF)

wd <- "path/"

# using base-R functions
df = read.csv(paste0(wd, "block.data.csv"))
df <- df[, 3:ncol(df)]

set.seed(123)
vars <- VSURF(df[, 2:length(df)],
              df[, 1], 
              parallel = TRUE,
              ntree = 2001, 
              RFimplem = "ranger")
```

using `data.table` functions
```
df = read.csv(paste0(wd, "block.data.csv"))
df[, c("x","y"):=NULL]

set.seed(123)
vars <- VSURF(df[, 2:length(df)],
              df[, 1], 
              parallel = TRUE,
              ntree = 2001, 
              RFimplem = "ranger")
```

Many thanks.

**Comment by robingenuer** [comment]
Hi @nikosGeography ,
Thanks for pointing this out.
I may miss something here, but it seems to me that the error is triggered before the `VSURF()` call in your example, when you select input and output variables in the first two arguments, no ?
I am not familiar with data.table, but if `ranger` is compatible with it, `VSURF` with `RFimplem = "ranger"` (as you use it) should be also. Did you try with "formula type" call with something as the following ?

```r
vars <- VSURF(Yname ~ .,
              data = df, 
              parallel = TRUE,
              ntree = 2001, 
              RFimplem = "ranger")
``` 
where `Yname` is the name of the columun associated to your output variable.

**Comment by nikosGeography** [comment]
You were right. By setting a formula (like you did `Yname ~ .`) the code worked fine even whe I imported the data using the `fread()` function from `data.table`.

**Comment by robingenuer** [comment]
Great then, thanks for your feedback about the use of `data.table` format.
