### ISSUE TITLE
How to determing variable selection？

### ISSUE THREAD

**Issue by timeresistance1996** [robingenuer/VSURF#9]
Hallo @robingenuer ,

    On VSURF, I am a novice, may I ask the difference between $varselect.thres, $varselect.interp, and $varselect.pred in VSURF results, and how to choose the final variable in general circumstances.

**Comment by robingenuer** [comment]
Hi @timeresistance1996 ,
The three different set of variables correspond to the three different steps of VSURF algorithm, and `varselect.pred` is a subset of `varselect.interp` which is also a subset of `varselect.thres`.
The first one, `varselect.thres` is usually not the final result you want to keep. You may see it as a necessary intermediate selection, especially in very high-dimension where you have a very large number of variables on your data.
The second one, `varselect.interp` is the set suited to answer the question "what are all the important/useful variables in your dataset ?" (whatever their correlation/redundancy).
The last one, `varselect.pred` is the smallest set which answer the question "what is the minimal set of variables necessary to keep good prediction performances with you random forests predictor ?" (in this case, the redundancy between the selected variables is reduced).

For more information, you could look at our R journal article on VSURF : https://journal.r-project.org/archive/2015-2/genuer-poggi-tuleaumalot.pdf

Best,
Robin

**Comment by timeresistance1996** [comment]
Thank you for your answer, it helps! 

    Please allow me to ask one more question. Usually, before constructing a random forest, we remove parameters with a correlation greater than 0.7 or 0.8. Do you think this step is necessary before running vsurf, or can I directly input all variables into vsurf for variable selection?
